import '../styles/styles.scss';

import { Roboto } from 'next/font/google';
import React from 'react';

import { RequestConfig } from '@/api/config';
import { Navbar } from '@/components/navbar';
import { CatalogProvider } from '@/contexts/catalog';
import { ConfigProvider } from '@/contexts/config';

import type { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Challenge Burger',
  description: 'Generated by create next app',
};

const roboto = Roboto({ weight: ['400', '500'], subsets: ['latin'] });

export default async ({ children }: Readonly<{ children: React.ReactNode }>) => {
  const data = await RequestConfig();

  const style: any = {
    '--system-background-color': data.webSettings.backgroundColour,
    '--system-banner-image': data.webSettings.bannerImage,
    '--system-nav-background-color': data.webSettings.navBackgroundColour,
    '--system-primary-color': data.webSettings.primaryColour,
    '--system-primary-color-hover': data.webSettings.primaryColourHover,
  };

  return (
    <html lang="en" style={style}>
      <body className={roboto.className} suppressHydrationWarning={true}>
        <ConfigProvider initialConfig={data}>
          <CatalogProvider>
            <header>
              <Navbar />
            </header>
            <main>{children}</main>
            <footer></footer>
          </CatalogProvider>
        </ConfigProvider>
      </body>
    </html>
  );
};
