import '../styles/styles.scss';

import { Roboto } from 'next/font/google';
import React, { ReactNode } from 'react';

import { RequestConfig } from '@/api/config';
import { Navbar } from '@/components/navbar';
import { BasketProvider } from '@/contexts/basket';
import { CatalogProvider } from '@/contexts/catalog';
import { ConfigProvider } from '@/contexts/config';

import type { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Challenge Burger',
  description: 'Generated by create next app',
};

const roboto = Roboto({ weight: ['300', '400', '500', '700'], subsets: ['latin'] });

export default async function Layout({ children }: Readonly<{ children: ReactNode }>) {
  const data = await RequestConfig();

  const style: any = {
    '--system-background-color': data.webSettings.backgroundColour,
    '--system-banner-image': data.webSettings.bannerImage,
    '--system-nav-background-color': data.webSettings.navBackgroundColour,
    '--system-primary-color': data.webSettings.primaryColour,
    '--system-primary-color-hover': data.webSettings.primaryColourHover,
  };

  return (
    <html lang={data.locale} style={style}>
      <body className={roboto.className} suppressHydrationWarning={true}>
        <ConfigProvider initialConfig={data}>
          <CatalogProvider>
            <BasketProvider>
              <header>
                <Navbar />
              </header>
              <main>{children}</main>
              <footer></footer>
            </BasketProvider>
          </CatalogProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
